### PR TITLE
SessionUaSdk::requestRead: read only if server is connected, else ignore

### PR DESCRIPTION
**Pull request by bkuner**
Hallo Ralph,
the combination of opcua and UaGate Server with many process variables has seriously problems at startup. The server connects lately and meanwhile the ioc fires read requests in a high rate - with its according failure messages. It ends up that not all process variables will be connected. Or the IOC restarts - without any failure message, not even segment fault.

This is because all records are processed at startup. The read_begin fails and you set SetIncomingEvent(ProcessReason::readFailure); This causes the record to process again and again. My workaround is to test ifConnected and if not to send  ProcessReason::none to prevent further processing. The idea is if there will come an connection and the record is IO/Intr then it will be processed by the dataChange interrupt and if SCAN is set it will process periodically. I'm not shure about all implications but it seems to run propper here.

### CODE REVIEW

**Comment by ralphlange** [comment]
The initial read commands are sent when the IOC connects to the server (following the session connection state change callback), not earlier.

Unless your records have PINI set (which they shouldn't) or are periodically scanned, I don't see why they would be processed early after reboot.

**Comment by bkuner** [comment]
I haven't set PINI, the records are IO/Intr and the (successfull) startup output is as follows. I deleted lines with the same error and replaced it with the tag '... n lines'. The base is 3-15-6 and the opcua 
version tag is 'Merge changes from v0.5.1' Without my patch the 'no incoming data output woild occur manny times.
To me it processes before the connection is established
Grüssle, Bernhard

@@@ Current time: Fri Aug 23 14:01:35 2019
@@@ Child process is shutting down, a new one will be restarted shortly
@@@ ^R or ^X restarts the child, ^Q quits the server

@@@ @@@ @@@ @@@ @@@
@@@ Received a sigChild for process 35675. The process was killed by signal 9
@@@ Restarting child "sioc61c"
@@@    (as ./st.cmd.SIOC61C)
@@@ The PID of new child "sioc61c" is: 36794
@@@ @@@ @@@ @@@ @@@
#!/opt/IOC/opcua/links/opcuaIoc/bin/linux-x86_64/opcuaIoc
# Change to Application top directory
cd /opt/IOC/opcua/links/opcuaIoc
########################################################### Set up Environment
epicsEnvSet IOC SIOC61C
epicsEnvSet IOCSH_PS1 "SIOC61C>"
epicsEnvSet LOG_DIR /opt/IOC/log
epicsEnvSet EPICS_CA_PUT_LOG_INET 192.168.48.97
epicsEnvSet STREAM_PROTOCOL_PATH db
dbLoadDatabase "dbd/opcuaIoc.dbd",0,0
opcuaIoc_registerRecordDeviceDriver pdbbase
############################################################ Configure drivers
opcuaCreateSession PAHBctrl "opc.tcp://192.168.210.148:4840" 0 y 
opcuaCreateSubscription PAHBCTRL PAHBctrl 200 0 0 
opcuaCreateSession PAHBcre "opc.tcp://192.168.210.149:4840" 0 y 
opcuaCreateSubscription PAHBCRE PAHBcre 200 0 0 
######################################################## Load record instances
cd /opt/IOC/BII-Controls/links/SIOC61C
dbLoadRecords db/DistVersion.db "IOC=SIOC61C,TOP=."
dbLoadRecords db/IOC-stats.db IOC=SIOC61C
dbLoadRecords "db/PAHB_Ctrl_Cur.db"
dbLoadRecords "db/PAHB_Ctrl_Pwr.db"
dbLoadRecords "db/PAHB_Ctrl_Temp.db"
dbLoadRecords "db/PAHB_Cre_ai1.db"
dbLoadRecords "db/PAHB_Cre_ai2.db"
dbLoadRecords "db/PAHB_Cre_ai3.db"
dbLoadRecords "db/PAHB_Cre_ai4.db"
dbLoadRecords "db/PAHB_Cre_ai5.db"
dbLoadRecords "db/PAHB_Cre_ai6.db"
dbLoadRecords "db/PAHB_Cre_ai7.db"
dbLoadRecords "db/PAHB_Cre_bi1.db"
dbLoadRecords "db/PAHB_Cre_bi2.db"
dbLoadRecords "db/PAHB_Cre_bi3.db"
dbLoadRecords "db/PAHB_Cre_bi4.db"
dbLoadRecords "db/PAHB_Cre_bi5.db"
dbLoadRecords "db/PAHB_Cre_bi6.db"
dbLoadRecords "db/PAHB_Cre_bi7.db"
########################################################### Configure IOC Core
# IOC Log Server Connection  0=enabled 1=disabled
setIocLogDisable 0
# Configure Access Security
asSetFilename /opt/IOC/AccessSecurity/links/PROD/no_security.acf
#################################################################### Start IOC
iocInit
Starting iocInit
############################################################################
## EPICS R3.15.6
## EPICS Base built Aug  7 2019
############################################################################
OPC UA Client Device Support v0.6.0-dev; using Unified Automation C++ Based OPC UA Client SDK
PAHB:Ctrl:cmdCircArcTestPuls Error in add_record : expected '=' in 'PAHBCTRL ns=2;s=S7-1.DB_CtrlSsaAll.Cmd Circ_Arc_TestPuls_All'
PV: PAHB:Ctrl:cmdCircArcTestPuls scanAdd: I/O Intr not valid

PAHB:Ctrl:cmdReset Error : unsupported conversion for outgoing data
...26 lines
PAHB:Ctrl:setCavPhs Error : unsupported conversion for outgoing data
cas warning: Configured TCP port was unavailable.
cas warning: Using dynamically assigned TCP port 45765,
cas warning: but now two or more servers share the same UDP port.
cas warning: Depending on your IP kernel this server may not be
cas warning: reachable with UDP unicast (a host's IP in EPICS_CA_ADDR_LIST)
epicsThreadRealtimeLock Warning: Unable to lock the virtual address space.
VM page faults may harm real-time performance.
OPC UA: Autoconnecting sessions
PAHB:Ctrl:cmdReset Error : unsupported conversion for outgoing data
... 23 lines
PAHB:Ctrl:cmdSsaDataRequest Error : unsupported conversion for outgoing data
PAHB:Ctrl:stFastILPinSA1 Error : no incoming data
...274 lines
PAHB:Cre:stCurS2M13 Error : no incoming data
PAHB:Ctrl:setCavVolt Error : PAHB:Cre:stCurS2M2 Error : no incoming data
unsupported conversion for outgoing data
PAHB:Cre:stCurS2M3 Error : no incoming data
PAHB:Ctrl:setRelPhs Error : unsupported conversion for outgoing data
PAHB:Cre:stCurS2M4 Error : no incoming data
PAHB:Ctrl:setCavPhs Error : unsupported conversion for outgoing data
PAHB:Cre:stCurS2M5 Error : no incoming data
PAHB:Cre:stCurS2M6 Error : no incoming data
PAHB:Ctrl:setLlRfRes1 Error : unsupported conversion for outgoing dataPAHB:Cre:stCurS2M7 Error : no incoming data

PAHB:Cre:stCurS2M8 Error : no incoming data
PAHB:Ctrl:setLlRfRes2 Error : unsupported conversion for outgoing dataPAHB:Cre:stCurS2M9 Error : no incoming data

PAHB:Cre:stCurS3Drv Error : no incoming data
PAHB:Ctrl:fwdLLRFEffPwr Error : unsupported conversion for outgoing data
PAHB:Ctrl:fwdLLRF_CvrdLoss Error : unsupported conversion for outgoing data
PAHB:Cre:stCurS3M1 Error : no incoming data
... 706 lines
PAHB:Cre:stRect5 Error : no incoming data
PAHB:Ctrl:fwdLLRFEffPwr Error : unsupported conversion for outgoing data
OPC UA session PAHBcre: connection status changed from Disconnected to Connected
OPC UA session PAHBcre: (registerNodes) registerNodes service failed with status BadNothingToDo
OPC UA session PAHBctrl: connection status changed from Disconnected to Connected
OPC UA session PAHBctrl: (registerNodes) registerNodes service failed with status BadNothingToDo
PAHB:Cre:stSumAlrmMnRect Error : incoming data out-of-bounds
PAHB:Cre:stRfOn Error : incoming data out-of-bounds
PAHB:Ctrl:cmdReset Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaRes1 Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaSupplOn Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaMdlOn Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaRfOn Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaReset Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaRes2 Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaRes3 Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaOff Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngWpModeOn Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngDrvFMaxAuto Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngDrvFMinAuto Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngDrvFMaxTipp Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngDrvFMinTipp Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngWpModeOff Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngStop Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngDrvRefPos Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngDrvClean Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngEnaCtrl Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdPlngDriveHome Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSignCuitExtIL Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdLlRfPhsCtrl Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdLlRfCtrlRf Error : unsupported conversion for outgoing data
PAHB:Ctrl:cmdSsaDataRequest Error : unsupported conversion for outgoing data
PAHB:Ctrl:setCavVolt Error : unsupported conversion for outgoing data
PAHB:Ctrl:setRelPhs Error : unsupported conversion for outgoing data
PAHB:Ctrl:setCavPhs Error : unsupported conversion for outgoing data
PAHB:Ctrl:setLlRfRes1 Error : unsupported conversion for outgoing data
PAHB:Ctrl:setLlRfRes2 Error : unsupported conversion for outgoing data
PAHB:Ctrl:fwdLLRFEffPwr Error : unsupported conversion for outgoing data
PAHB:Ctrl:fwdLLRF_CvrdLoss Error : unsupported conversion for outgoing data
PAHB:Ctrl:stSignCuitMains24V Error : incoming data out-of-bounds
PAHB:Ctrl:stSignCuitstMains24VGnd Error : incoming data out-of-bounds
PAHB:Ctrl:cmdSignCuitExtIL Error : incoming data out-of-bounds
PAHB:Ctrl:stSignCuitMains24V Error : incoming data out-of-bounds
PAHB:Ctrl:stSignCuitstMains24VGnd Error : incoming data out-of-bounds
PAHB:Ctrl:stPlngHomePosition Error : incoming data out-of-bounds
PAHB:Ctrl:stSignCuitExtIL Error : incoming data out-of-bounds
PAHB:Ctrl:stLLRFHfWayInLevel Error : incoming data out-of-bounds
PAHB:Ctrl:fwdLLRFEffPwr Error : incoming data out-of-bounds
PAHB:Ctrl:stPhsMeasRfLevelInt Error : incoming data out-of-bounds
PAHB:Ctrl:stPlngHomePosition Error : incoming data out-of-bounds
PAHB:Ctrl:stSignCuitExtIL Error : incoming data out-of-bounds
PAHB:Ctrl:stLLRFHfWayInLevel Error : incoming data out-of-bounds
iocRun: All initialization complete
## Report Installed and Configured I/O-Hardware Information
dbior 0 1 > /opt/IOC/log/Database/SIOC61C.dbior
dbhcr     > /opt/IOC/log/Database/SIOC61C.dbhcr
dbl       > /opt/IOC/log/Database/SIOC61C.dbl
system "cp iocBoot/version /opt/IOC/log/Database/SIOC61C.version"
PAHB:Ctrl:stPhsMeasRfLevelInt Error : incoming data out-of-bounds
system "pwd | tee /opt/IOC/log/Database/SIOC61C.pwd"
/net/nfs/srv/IOC/BII-Controls/dist/2019-08-22T16:45:34
SIOC61C>PAHB:Cre:stSumAlrmMnRect Error : incoming data out-of-bounds
PAHB:Cre:stRfOn Error : incoming data out-of-bounds

SIOC61C>[disconnect]

**Comment by ralphlange** [comment]
Yes, true, the records are processed: to update their status to `COMM/INVALID`.
However, that processing should not trigger any low level read or write services nor any data conversions (the error messages you are seeing). There is something going wrong, but I would rather like to fix the root cause to avoid `read_request()` being called in the first place. Your fix might still be needed to ignore 'real' processing requests (periodic scan or CA activity) while the connection is down.

Possibly related question:
As you are using a high number of records - have you set the length of the EPICS Base internal queues accordingly? Since all OPC UA nodes are being read when a connection comes up, the queues should have room for all records with a DTYP of OPCUA.
(Your observation of not all records being connected could be caused a queue overflow.)

First error message: looks like the node name in one of your records contains a space character (that would need to be escaped).

**Comment by ralphlange** [comment]
This is related to #54 - it is basically a possible implementation.

**Comment by ralphlange** [comment]
Implemented by f85b360dcef63855eb1e7537a98a505a8a1ab31b (on branch release/5.0); cherry-picked to master as 96a2de72442e32b6fe6cd35bcd8a89a21caecdb2

**Comment by ralphlange** [comment]
Thanks. This pull request has been integrated manually.

**Pull request closed without merging**
