### PR TITLE
Refactor/link parser

### PR DESCRIPTION
**Pull request by kivel**
Refactor of the linkParser, plus addition of string literal support in inp/out links.

refactor:
The use of a tokenizer allows for `send`, `sep` and `seq` to be removed from the various places in the parsing routine. Thus, the procedural structure becomes clearer.

string literals:
This feature was added to accommodate the Beckhoff EK-9160 IoT coupler.
The coupler exposes the EtherCAT bus with string names like this `Slave 2 (EL1124).Channel 1.Input`.
Due to the presence of spaces, and potentially more delimiters used for tokenization, the parser consumes the string within `'`-quotes as is.
The `INP` example looks like this: `field(INP,  "@$(SUBS) ns=4;s='Slave 2 (EL1124).Channel 1.Input'")`

tested on the `feature/open62541-integration` branch, build on Debian 12 x86_64, using epics base R7.0.7

### CODE REVIEW

**Comment by dirk-zimoch** [comment]
> Due to the presence of spaces, and potentially more delimiters...

I guess that is why Siemens quotes everything. But the Siemens equivalent would be:
`"Slave 2 (EL1124)"."Channel 1"."Input"`
That forces the user to write:
`field(INP,  "@$(SUBS) ns=4;s=\"Slave 2 (EL1124)\".\"Channel 1.Input\"")`
and even worse if the node ID is a macro like
`field(INP, "@$(SUBS) $(NODEID)")`
one has to write in the substitution file:
`"ns=4;s=\\\"Slave 2 (EL1124)\\\".\\\"Channel 1.Input\\\""`

I wish the parser could magically add the quotes for Siemens servers.

**Comment by kivel** [comment]
Are for Siemes servers _all_ nodeid components separated by a '.' wrapped in quotes ... always?

**Comment by dirk-zimoch** [comment]
That would be too easy. I have found entries without quotes, but those all have NodeClass=Object. But some Objects do have quoted node ids. All nodes with NodeClass=Variable seem to be quoted, However, sometimes `.` is part of the quoted string, sometimes not. And sometimes, only some parts are quoted, maybe only for NodeClass=Method.

Examples I found on our test PLC are:
* `ns=3;s=DataBlocksGlobal` an Object
* `ns=3;s="mySiOME_Export_Data"` another Object
* `ns=3;s="DataStatic"."myArrayBool"` a Variable
* `ns=3;s="mySiOME_Export_Data"."mySiOME_Export.Server.Namespaces.http://myManufacturer.org/myInterface.NamespaceUri"` another Variable
* `ns=3;s="InstUaMethodAdding".Method` a Method.

The name space in question is `http://www.siemens.com/simatic-s7-opcua`.

**Comment by kivel** [comment]
So, since the linkparser has no knowledge of the data type on the server - and since the connection is not even established - there basically is no procedural way to derive where quotes need to be placed.

**Pull request closed without merging**
